services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  webserver:
    build: .
    image: final_project_airflow:latest   
    restart: always
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/keys/purwadika-502e43f1636d.json
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data_generator:/opt/airflow/data_generator
      - ./scripts:/opt/airflow/scripts
      - ./dbt_ecommerce:/opt/airflow/dbt_ecommerce
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./keys:/opt/airflow/keys
    ports:
      - "8080:8080"
    command: webserver

  scheduler:
    build: .
    image: final_project_airflow:latest   
    restart: always
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/keys/purwadika-502e43f1636d.json
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data_generator:/opt/airflow/data_generator
      - ./scripts:/opt/airflow/scripts
      - ./dbt_ecommerce:/opt/airflow/dbt_ecommerce
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ./keys:/opt/airflow/keys
    command: scheduler

volumes:
  postgres_data:
