version: 2

sources:
  - name: raw
    database: purwadika
    schema: jcdeol005_finalproject_eko_raw
    tables:
      - name: suppliers
      - name: users
      - name: products
      - name: orders
      - name: order_items
      - name: payments
      - name: shipments
      - name: reviews

models:
# --- Staging models ---
  - name: stg_suppliers
    columns:
      - name: supplier_id
        tests: [not_null, unique]

  - name: stg_users
    columns:
      - name: user_id
        tests: [not_null, unique]

  - name: stg_products
    columns:
      - name: product_id
        tests: [not_null, unique]

  - name: stg_orders
    columns:
      - name: order_id
        tests: [not_null, unique]

  - name: stg_order_items
    columns:
      - name: order_item_id
        tests: [not_null, unique]
      - name: line_total
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              arguments:
                expression: "{{ column_name }} >= 0"

  - name: stg_payments
    columns:
      - name: payment_id
        tests: [not_null, unique]

  - name: stg_shipments
    columns:
      - name: shipment_id
        tests: [not_null, unique]

  - name: stg_reviews
    columns:
      - name: review_id
        tests: [not_null, unique]

# --- Warehouse models ---
  - name: dim_date
    description: "Date dimension for DWH"
    tests:
      - not_null:
          column_name: date
  - name: dim_users
    description: "Customers dimension"
    columns:
      - name: user_id
        tests:
          - not_null
          - unique
      - name: first_order_date
        tests:
          - not_null
  - name: dim_products
    description: "Products dimension"
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
  - name: dim_suppliers
    description: "Suppliers dimension"
    columns:
      - name: supplier_id
        tests:
          - not_null
          - unique
  - name: dim_payments
    description: "Payments dimension"
    columns:
      - name: payment_id
        tests:
          - not_null
          - unique
  - name: fact_orders
    description: "Fact table at order granularity"
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: user_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_users')
              field: user_id
      - name: order_date
        tests:
          - not_null
      - name: order_total
        tests:
          - not_null
