name: 'dbt_ecommerce'
version: '1.0.0'
config-version: 2

profile: 'ecommerce'

model-paths: ["models"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  dbt_ecommerce:
    staging:
      +schema: jcdeol005_finalproject_eko_staging
      +materialized: table
    warehouse:
      +schema: jcdeol005_finalproject_eko_dw
      +materialized: table