ecommerce:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: purwadika
      dataset: temp_dataset
      threads: 4
      keyfile: /opt/airflow/keys/purwadika-502e43f1636d.json
      timeout_seconds: 300
      location: asia-southeast2
      priority: interactive
